language: java
# use Java 8
jdk:
  #- oraclejdk8
  - openjdk8

sudo: false
script: ./mvnw --activate-profiles dev clean verify

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr