language: java
sudo: true
dist: trusty

# use Java 8
#jdk: oraclejdk8
jdk:
  - openjdk8

script: ./mvnw clean install

addons:
  apt:
    packages:
#      -oracle-java8-installer

before_install:
  - chmod +x mvnw


jobs:
  include:
    - stage: Test
      script: ./mvnw clean test


cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr