language: java
sudo: true
dist: trusty

# use Java 8
#jdk: oraclejdk8
jdk: openjdk8

addons:
  apt:
    packages:
#      -oracle-java8-installer

before_install:
#  - chmod +x mvnw

script: ./mvnw --activate-profiles dev clean install

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr