version: "3"

services:
  properties:
    container_name: escalade-properties
    image: properties-server:pedsf
    environment:
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_SECRET}
    ports:
    - "8888:8888"
    networks:
      net:
        ipv4_address: 10.5.0.2


  db:
    container_name: escalade-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: Escalade_Api
      POSTGRES_PASSWORD: Escalade_Api
      POSTGRES_DB: escalade
      PGDATA: /TMP
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 10.5.0.5

  escalade:
    container_name: escalade-web
    restart: on-failure
    build: ./
    environment:
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_SECRET}
      - spring.cloud.config.uri=http://10.5.0.2:8888
      - spring.datasource.url=jdbc:postgresql://10.5.0.5:5432/escalade
    volumes:
      - //f/images:/images
    depends_on:
      - "properties"
      - "db"
    ports:
      - "9090:9090"
    networks:
      net:
        ipv4_address: 10.5.0.3


volumes:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /f/PostgreSQL/docker/escalade

#networks:
#  default:
#    external:
#      name: escalade-net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

