version: "3"

services:
  properties-server:
    container_name: properties_server
    image: properties-server:pedsf
    environment:
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_SECRET}
    ports:
    - "8888:8888"
    networks:
      net:
        ipv4_address: 10.5.0.2


  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: Escalade_Api
      POSTGRES_PASSWORD: Escalade_Api
      POSTGRES_DB: escalade
      PGDATA: /data
    volumes:
        - /PostgreSQL/data/escalade:/data
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 10.5.0.5

  escalade:
    container_name: escalade
    build: ./
    environment:
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_SECRET}
      - spring.cloud.config.uri=http://10.5.0.2:8888
      - spring.datasource.url=jdbc:postgresql://10.5.0.5:5432/escalade
    volumes:
      - /images:/images
    depends_on:
      - properties-server
      - postgres
    ports:
      - "9090:9090"
    networks:
      net:
        ipv4_address: 10.5.0.3


#networks:
#  default:
#    external:
#      name: escalade-network

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

